name: CI

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        
      - run: find . -type f -exec sed -i 's/https:\/\/localhost:7181/https:\/\/menza.alb1.hu/g' {} +
      
      - run: dotnet publish Menza.Server/Menza.Server.csproj -c Release -o ./publish -r linux-x64 -p:PublishTrimmed=true --self-contained
      
      - run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user stop menza.service

      - run: cp -r publish/* /var/www/Menza/

      - run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart menza.service
