name: CI

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user stop menza.service

      - name: Publish
        run: dotnet publish Menza.Server/Menza.Server.csproj -c Release -o /var/www/Menza

      - run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart menza.service
